<!--
=========================================================
* Material Dashboard 2 - v3.1.0
=========================================================

* Product Page: https://www.creative-tim.com/product/material-dashboard
* Copyright 2023 Creative Tim (https://www.creative-tim.com)
* Licensed under MIT (https://www.creative-tim.com/license)
* Coded by Creative Tim

=========================================================

* The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
-->
<?php

/*
ini_set('display_errors', 1);
ini_set('display_startup_errors', 1);
error_reporting(E_ALL);
*/

$servername = "localhost";
$username = "wheeliams_dashboard";
$password = "EGalEh1x..r3";
$dbname = "wheeliams_dashboard";

// Create connection
$conn = new mysqli($servername, $username, $password, $dbname);
// Check connection
if ($conn->connect_error) {
  die("Connection failed: " . $conn->connect_error);
}

// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
$ch = curl_init();

curl_setopt($ch, CURLOPT_URL, 'https://wheeliamsltd.myshopify.com/admin/api/2023-10/orders.json?status=open&limit=250');
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'GET');


$headers = array();
$headers[] = 'X-Shopify-Access-Token: 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';
curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

$result = json_decode(curl_exec($ch),true);
if (curl_errno($ch)) {
    echo 'Error:' . curl_error($ch);
}
curl_close($ch);

$result = array_reverse($result['orders'], true);
$count = count($result);
//print_r($result);

function getProduct($id){
	// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
	$ch = curl_init();
	
	curl_setopt($ch, CURLOPT_URL, 'https://wheeliamsltd.myshopify.com/admin/api/2023-10/products/'.$id.'.json');
	curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
	curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'GET');
	
	
	$headers = array();
	$headers[] = 'X-Shopify-Access-Token: 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';
	curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);
	
	$result = curl_exec($ch);
	if (curl_errno($ch)) {
	    echo 'Error:' . curl_error($ch);
	}
	curl_close($ch);

}

function getMeta($id){
	// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
	$ch = curl_init();
	
	curl_setopt($ch, CURLOPT_URL, 'https://wheeliamsltd.myshopify.com/admin/api/2023-07/metafields.json?metafield%5Bowner_id%5D='.$id.'&metafield%5Bowner_resource%5D=variants');
	curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
	curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'GET');
	
	
	$headers = array();
	$headers[] = 'X-Shopify-Access-Token: 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';
	curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);
	
	$result = json_decode(curl_exec($ch),true);
	if (curl_errno($ch)) {
	    echo 'Error:' . curl_error($ch);
	}
	curl_close($ch);
	
	foreach($result['metafields'] as $meta){
		if($meta['key']=='dashboard_name'){
			return $meta['value'];
		}
	}

}

function getProductDB($conn,$id){
	
	if($id<>''){
		$sql = "SELECT * FROM shopify_products WHERE productid=".$id;
		$result = $conn->query($sql);
		if ($result->num_rows == 1) {
			// output data of each row
			while($row = $result->fetch_assoc()) {
				return $row;
			}
		}
	}
	
}

function getVariantDB($conn,$id){
	
	if($id<>''){
		$sql = "SELECT * FROM shopify_products WHERE variantid=".$id;
		$result = $conn->query($sql);
		if ($result->num_rows == 1) {
			// output data of each row
			while($row = $result->fetch_assoc()) {
				return $row;
			}
		}
	}
	
}

function getItemStatus($conn,$order,$id){
	$sql = "SELECT * FROM order_items WHERE orderid='".$order."' AND item='".$id."'";
	$result = $conn->query($sql);
	if ($result->num_rows == 1) {
		return true;
	}else{
		return false;
	}
}
?>
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link rel="apple-touch-icon" sizes="76x76" href="../assets/img/apple-icon.png">
  <link rel="icon" type="image/png" href="../assets/img/favicon.png">
  <title>
    Wheeliams Dashboard
  </title>
  <!--     Fonts and icons     -->
  <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700,900|Roboto+Slab:400,700" />
  <!-- Nucleo Icons -->
  <link href="../assets/css/nucleo-icons.css" rel="stylesheet" />
  <link href="../assets/css/nucleo-svg.css" rel="stylesheet" />
  <!-- Font Awesome Icons -->
  <script src="https://kit.fontawesome.com/42d5adcbca.js" crossorigin="anonymous"></script>
  <!-- Material Icons -->
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons+Round" rel="stylesheet">
  <!-- CSS Files -->
  <link id="pagestyle" href="../assets/css/material-dashboard.css?v=3.1.0" rel="stylesheet" />
  <!-- Nepcha Analytics (nepcha.com) -->
  <!-- Nepcha is a easy-to-use web analytics. No cookies and fully compliant with GDPR, CCPA and PECR. -->
  <script defer data-site="YOUR_DOMAIN_HERE" src="https://api.nepcha.com/js/nepcha-analytics.js"></script>
  <style>
	  tr.strike p{
		  text-decoration: line-through;
		  opacity:0.8;
	  }
	  table tr.first-line td{
		  border-top:2px solid #777 !important;
	  }
  </style>
</head>

<body class="g-sidenav-show  bg-gray-200">
<!--
  <aside class="sidenav navbar navbar-vertical navbar-expand-xs border-0 border-radius-xl my-3 fixed-start ms-3   bg-gradient-dark" id="sidenav-main">
    <div class="sidenav-header">
      <i class="fas fa-times p-3 cursor-pointer text-white opacity-5 position-absolute end-0 top-0 d-none d-xl-none" aria-hidden="true" id="iconSidenav"></i>
      <a class="navbar-brand m-0" href=" https://demos.creative-tim.com/material-dashboard/pages/dashboard " target="_blank">
        <img src="../assets/img/wheeliams.avif" class="navbar-brand-img h-100" alt="main_logo">
      </a>
    </div>
    <hr class="horizontal light mt-0 mb-2">
    <div class="collapse navbar-collapse  w-auto " id="sidenav-collapse-main">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link text-white active bg-gradient-primary " href="/">
            <div class="text-white text-center me-2 d-flex align-items-center justify-content-center">
              <i class="material-icons opacity-10">dashboard</i>
            </div>
            <span class="nav-link-text ms-1">Dashboard</span>
          </a>
        </li>
      </ul>
    </div>
    <div class="sidenav-footer position-absolute w-100 bottom-0 ">
      <div class="mx-3">
        
      </div>
    </div>
  </aside>
-->
  <main class="main-content position-relative max-height-vh-100 h-100 border-radius-lg ">
    <!-- Navbar -->
    <nav class="navbar navbar-main navbar-expand-lg px-0 mx-4 shadow-none border-radius-xl" id="navbarBlur" data-scroll="true">
      <div class="container-fluid py-1 px-3">
        <nav aria-label="breadcrumb">
          <ol class="breadcrumb bg-transparent mb-0 pb-0 pt-1 px-0 me-sm-6 me-5">
            <li class="breadcrumb-item text-sm"><a class="opacity-5 text-dark" href="javascript:;">Pages</a></li>
            <li class="breadcrumb-item text-sm text-dark active" aria-current="page">Dashboard</li>
          </ol>
          <h6 class="font-weight-bolder mb-0">Dashboard</h6>
        </nav>
        <div class="collapse navbar-collapse mt-sm-0 mt-2 me-md-0 me-sm-4" id="navbar">
          
        </div>
      </div>
    </nav>
    <!-- End Navbar -->
    <div class="container-fluid py-4">
      <div class="row">
        <div class="col-12">
          <div class="card my-4">
            <div class="card-header p-0 position-relative mt-n4 mx-3 z-index-2">
              <div class="bg-gradient-primary shadow-primary border-radius-lg pt-4 pb-3">
                <h6 class="text-white text-capitalize ps-3">Open Orders (<?= $count ?>)</h6>
              </div>
            </div>
            <div class="card-body px-0 pb-2">
              <div class="table-responsive p-0">
                <table class="table align-items-center mb-0">
                  <thead>
                    <tr>
                      <th class="text-uppercase text-secondary font-weight-bolder opacity-7 ps-2">Items</th>
                      <th class="text-uppercase text-secondary font-weight-bolder opacity-7 ps-2">Quantity</th>
                      <th class="text-center text-uppercase text-secondary font-weight-bolder opacity-7 ps-2">Complete</th>
                      <th class="text-uppercase text-secondary font-weight-bolder opacity-7">Order</th>
                      <th class="text-center text-uppercase text-secondary font-weight-bolder opacity-7">Order Date</th>
                    </tr>
                  </thead>
                  <tbody>
	                <?php
		            foreach($result as $Order){
						//print_r($Order);
						$show = false;
						$products = '';
						
						$i=1;
						
						foreach($Order['line_items'] as $item){
							$productData = getProductDB($conn,$item['product_id']);
							$variantData = getVariantDB($conn,$item['variant_id']);
							if($productData['showproduct']!==0 OR $variantData['showproduct']!==0){
								$show = true;
							}
						}
						
						if($show){
						
							$dates = explode("T", $Order['created_at']);
							$dates = explode("-", $dates[0]);
							$date = "$dates[2]/$dates[1]/$dates[0]";
							
							
/*
							echo '
							<tr>
		                      <td>
		                        <div class="d-flex px-2 py-1">
		                          <div class="d-flex flex-column justify-content-center">
		                            <h6 class="mb-0 text-sm">'.$Order['name'].'</h6>
		                          </div>
		                        </div>
		                      </td>
		                      <td>';
		                     	$item = $Order['line_items'][0];
		                     	$productData = getProductDB($conn,$item['product_id']);
								$variantData = getVariantDB($conn,$item['variant_id']);
								if($productData['showproduct']!==0){
									if($variantData){
										echo '<p class="font-weight-bold mb-0 text-sm">'.$variantData['dashboardtitle'].'</p>';
									}elseif($productData){
										echo '<p class="font-weight-bold mb-0 text-sm">'.$productData['dashboardtitle'].'</p>';
									}else{
										echo '<p class="font-weight-bold mb-0 text-sm">'.$item['title'].'</p>';
									}
								}
							echo '
		                      </td>
		                      <td class="align-middle text-center text-sm">
		                     	 <input type="checkbox" class="complete" data-order-id="'.$Order['name'].'" data-item-id="0" ';
		                     	 if(getItemStatus($conn,$Order['name'],0)){echo 'CHECKED';} echo ' />
		                      </td>
		                      <td class="align-middle text-center text-sm">
		                        <span class="text-secondary font-weight-bold">'.$date.'</span>
		                      </td>
		                    </tr>';
*/
							
							if(count($Order['line_items'])>0){
								$y = 0;
								foreach($Order['line_items'] as $item){
									
									$productData = getProductDB($conn,$item['product_id']);
											$variantData = getVariantDB($conn,$item['variant_id']);
											if($productData['showproduct']!=='0' AND $item['fulfillable_quantity']>0){
												
												if($i>0){
													echo '
													<tr class="';if(getItemStatus($conn,$Order['name'],$item['id'])){echo 'strike';} if($y==0){echo ' first-line';}echo '">
								                      <td>';
													
														
															$show = true;
															if($variantData){
																echo '<p class="font-weight-bold mb-0 text-sm">'.$variantData['dashboardtitle'].'</p>';
															}elseif($productData){
																echo '<p class="font-weight-bold mb-0 text-sm">'.$productData['dashboardtitle'].'</p>';
															}else{
																echo '<p class="font-weight-bold mb-0 text-sm">'.$item['title'].'</p>';
															}
														
					
													echo '
								                      </td>
								                      <td class="align-middle text-center text-sm">
								                      	<p class="font-weight-bold mb-0 text-sm">'.$item['fulfillable_quantity'].'</p>
								                      </td>
								                      <td class="align-middle text-center text-sm">
								                     	 <input type="checkbox" class="complete" data-order-id="'.$Order['name'].'" data-item-id="'.$item['id'].'" ';
													 	 if(getItemStatus($conn,$Order['name'],$item['id'])){echo 'CHECKED';} echo ' />
								                      </td>
								                      <td>
								                        <div class="d-flex px-2 py-1">
								                          <div class="d-flex flex-column justify-content-center">
								                            <h6 class="mb-0 text-sm">'; if($i>=0){echo $Order['name'];} echo '</h6>
								                          </div>
								                        </div>
								                      </td>
								                      <td class="align-middle text-center text-sm">'; if($i>=0){echo $date;} echo '
								                      </td>
								                    </tr>';
								                    $y++;
								                    }
						                    	}
						                    	$i++;
			                    	}
							}		
					
						}
					}
                    ?>

                  </tbody>
                </table>
              </div>
            </div>
          </div>
        </div>
      </div>
      <footer class="footer py-4  ">
        <div class="container-fluid">
          <div class="row align-items-center justify-content-lg-between">
            <div class="col-lg-6 mb-lg-0 mb-4">
              <div class="copyright text-center text-sm text-muted text-lg-start">
                © <script>
                  document.write(new Date().getFullYear())
                </script>
                Wheeliams Limited.
              </div>
            </div>
            <div class="col-lg-6">
              <ul class="nav nav-footer justify-content-center justify-content-lg-end">
                <li class="nav-item">
                  <a href="https://hellotechnology.co.uk" class="nav-link text-muted" target="_blank">Built by Hello Technology</a>
                </li>
              </ul>
            </div>
          </div>
        </div>
      </footer>
    </div>
  </main>
  <!--   Core JS Files   -->
  <script src="../assets/js/core/popper.min.js"></script>
  <script src="../assets/js/core/bootstrap.min.js"></script>
  <script src="../assets/js/plugins/perfect-scrollbar.min.js"></script>
  <script src="../assets/js/plugins/smooth-scrollbar.min.js"></script>
  <script>
    var win = navigator.platform.indexOf('Win') > -1;
    if (win && document.querySelector('#sidenav-scrollbar')) {
      var options = {
        damping: '0.5'
      }
      Scrollbar.init(document.querySelector('#sidenav-scrollbar'), options);
    }
  </script>
  <!-- Github buttons -->
  <script async defer src="https://buttons.github.io/buttons.js"></script>
  <!-- Control Center for Material Dashboard: parallax effects, scripts for the example pages etc -->
  <script src="../assets/js/material-dashboard.min.js?v=3.1.0"></script>
  
  <script
			  src="https://code.jquery.com/jquery-3.7.1.min.js"
			  integrity="sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo="
			  crossorigin="anonymous"></script>
  <script>
	$('.complete').click(function(){
		var pOrder = $(this).data('order-id');
		var pItem = $(this).data('item-id');
		$.post( "update.php", { order: pOrder, item: pItem } );
		if($(this).is(':checked')){
			$(this).parent().parent().addClass('strike');
		}else{
			$(this).parent().parent().removeClass('strike');
		}
	});  
  </script>
</body>

</html>