<?php if (!defined('PERCH_RUNWAY')) include($_SERVER['DOCUMENT_ROOT'].'/admin/runtime.php'); ?>
<?php

if(!perch_member_logged_in()){
	header("location:/sign-in/");
}	

$servername = "localhost";
$username = "wheeliams_dashboard";
$password = "EGalEh1x..r3";
$dbname = "wheeliams_dashboard";

// Create connection
$conn = new mysqli($servername, $username, $password, $dbname);
// Check connection
if ($conn->connect_error) {
  die("Connection failed: " . $conn->connect_error);
}

// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
$ch = curl_init();

curl_setopt($ch, CURLOPT_URL, 'https://wheeliamsltd.myshopify.com/admin/api/2023-10/orders.json?status=open&limit=250');
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'GET');


$headers = array();
$headers[] = 'X-Shopify-Access-Token: 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';
curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

$result = json_decode(curl_exec($ch),true);
if (curl_errno($ch)) {
    echo 'Error:' . curl_error($ch);
}
curl_close($ch);

$result = array_reverse($result['orders'], true);
$count = count($result);
//print_r($result);

function getProduct($id){
	// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
	$ch = curl_init();
	
	curl_setopt($ch, CURLOPT_URL, 'https://wheeliamsltd.myshopify.com/admin/api/2023-10/products/'.$id.'.json');
	curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
	curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'GET');
	
	
	$headers = array();
	$headers[] = 'X-Shopify-Access-Token: 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';
	curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);
	
	$result = curl_exec($ch);
	if (curl_errno($ch)) {
	    echo 'Error:' . curl_error($ch);
	}
	curl_close($ch);

}

function getMeta($id){
	// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
	$ch = curl_init();
	
	curl_setopt($ch, CURLOPT_URL, 'https://wheeliamsltd.myshopify.com/admin/api/2023-07/metafields.json?metafield%5Bowner_id%5D='.$id.'&metafield%5Bowner_resource%5D=variants');
	curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
	curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'GET');
	
	
	$headers = array();
	$headers[] = 'X-Shopify-Access-Token: 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';
	curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);
	
	$result = json_decode(curl_exec($ch),true);
	if (curl_errno($ch)) {
	    echo 'Error:' . curl_error($ch);
	}
	curl_close($ch);
	
	foreach($result['metafields'] as $meta){
		if($meta['key']=='dashboard_name'){
			return $meta['value'];
		}
	}

}

function getProductDB($conn,$id){
	
	if($id<>''){
		$sql = "SELECT * FROM shopify_products WHERE productid=".$id;
		$result = $conn->query($sql);
		if ($result->num_rows == 1) {
			// output data of each row
			while($row = $result->fetch_assoc()) {
				return $row;
			}
		}
	}
	
}

function getVariantDB($conn,$id){
	
	if($id<>''){
		$sql = "SELECT * FROM shopify_products WHERE variantid=".$id;
		$result = $conn->query($sql);
		if ($result->num_rows == 1) {
			// output data of each row
			while($row = $result->fetch_assoc()) {
				return $row;
			}
		}
	}
	
}

function getItemStatus($conn,$order,$id){
	$sql = "SELECT * FROM order_items WHERE orderid='".$order."' AND item='".$id."'";
	$result = $conn->query($sql);
	if ($result->num_rows == 1) {
		return true;
	}else{
		return false;
	}
}
?>
<?php
perch_layout('header');
?>
<main class="full">
	<h1>Dashboard</h1>
	<section>
		<header class="tabs">
			<ul>
				<li><button data-tab="jobs" class="active">Jobs List</button></li>
				<li><button data-tab="items">Items Required</button></li>
			</ul>
		</header>
		<article>
			<div class="tab jobs">
			<div class="table-container">
                <table class="">
                  <thead>
                    <tr>
                      <th>Items</th>
                      <th>Quantity</th>
                      <th>Complete</th>
                      <th>Order</th>
                      <th>Order Date</th>
                    </tr>
                  </thead>
                  <?php
										  // ── NEW: accumulator for the item totals summary ──
										  $itemTotals = [];
				  
										  foreach($result as $Order){
											  $show = false;
				  
											  foreach($Order['line_items'] as $item){
												  $productData = getProductDB($conn,$item['product_id']);
												  $variantData = getVariantDB($conn,$item['variant_id']);
												  if($productData['showproduct']!==0 OR $variantData['showproduct']!==0){
													  $show = true;
												  }
											  }
				  
											  if($show){
												  $dates = explode("T", $Order['created_at']);
												  $dates = explode("-", $dates[0]);
												  $date = "$dates[2]/$dates[1]/$dates[0]";
				  
												  if(count($Order['line_items'])>0){
													  $y = 0;
													  $i = 1;
													  foreach($Order['line_items'] as $item){
														  $productData = getProductDB($conn,$item['product_id']);
														  $variantData = getVariantDB($conn,$item['variant_id']);
				  
														  if($productData['showproduct']!=='0' AND $item['fulfillable_quantity']>0){
															  if($i>0){
				  
																  // ── Store status once, reuse below ──
																  $isComplete = getItemStatus($conn,$Order['name'],$item['id']);
				  
																  // ── Resolve the display label the same way the table does ──
																  if($variantData){
																	  $label = $variantData['dashboardtitle'];
																  } elseif($productData){
																	  $label = $productData['dashboardtitle'];
																  } else {
																	  $label = $item['title'];
																  }
				  
																  // ── Only count items that are NOT struck through ──
																  if(!$isComplete){
																	  if(!isset($itemTotals[$label])){
																		  $itemTotals[$label] = 0;
																	  }
																	  $itemTotals[$label] += $item['fulfillable_quantity'];
																  }
				  
																  echo '<tr class="';
																  if($isComplete){ echo 'strike'; }
																  if($y==0){ echo ' first-line'; }
																  echo '">
																	  <td>';
																		  echo '<p>'.$label.'</p>';
																	  echo '</td>
																	  <td>
																		  <p>'.$item['fulfillable_quantity'].'</p>
																	  </td>
																	  <td>
																		  <input type="checkbox" class="complete"
																			  data-order-id="'.$Order['name'].'"
																			  data-item-id="'.$item['id'].'" ';
																		  if($isComplete){ echo 'CHECKED'; }
																	  echo ' />
																	  </td>
																	  <td>
																		  <div>'.$Order['name'].'</div>
																	  </td>
																	  <td>'.$date.'</td>
																  </tr>';
				  
																  $y++;
															  }
														  }
														  $i++;
													  }
												  }
											  }
										  }
										  ?>
									  </tbody>
								  </table>
							  </div>
			</div>
			<div class="tab items">

					  <div class="table-container">
						  <table>
							  <thead>
								  <tr>
									  <th>Items</th>
									  <th>Quantity Required</th>
								  </tr>
							  </thead>
							  <tbody>
								  <?php
								  // Optional: sort alphabetically so it's easy to scan
								  ksort($itemTotals);
								  foreach($itemTotals as $label => $qty): ?>
								  <tr>
									  <td><?php echo htmlspecialchars($label); ?></td>
									  <td><?php echo $qty; ?></td>
								  </tr>
								  <?php endforeach; ?>
							  </tbody>
						  </table>
					  </div>

			</div>
						  </article>
	</section>
				  </main>
				  <script>
					  document.querySelectorAll('.tabs button').forEach(button => {
						  button.addEventListener('click', () => {
							  const target = button.dataset.tab;
					  
							  document.querySelectorAll('.tabs button').forEach(btn => btn.classList.remove('active'));
							  button.classList.add('active');
					  
							  document.querySelectorAll('.tab').forEach(tab => {
								  tab.style.display = tab.classList.contains(target) ? 'block' : 'none';
							  });
						  });
					  });
					  
					  // Show the first tab by default
					  document.querySelector('.tabs button').click();
				  </script>
				  
				  <?php perch_layout('footer'); ?>