<?php
ini_set('display_errors', 1);
ini_set('display_startup_errors', 1);
error_reporting(E_ALL);

$servername = "localhost";
$username = "wheeliams_dashboard";
$password = "EGalEh1x..r3";
$dbname = "wheeliams_dashboard";

// Create connection
$conn = new mysqli($servername, $username, $password, $dbname);
// Check connection
if ($conn->connect_error) {
  die("Connection failed: " . $conn->connect_error);
}

$conn->query('TRUNCATE TABLE shopify_products');

// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
$ch = curl_init();

curl_setopt($ch, CURLOPT_URL, 'https://wheeliamsltd.myshopify.com/admin/api/2023-10/products.json?limit=250');
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'GET');


$headers = array();
$headers[] = 'X-Shopify-Access-Token: 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';
curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

$result = json_decode(curl_exec($ch),true);
if (curl_errno($ch)) {
    echo 'Error:' . curl_error($ch);
}
curl_close($ch);

function getMeta($id,$type){
	// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
	$ch = curl_init();
	
	curl_setopt($ch, CURLOPT_URL, 'https://wheeliamsltd.myshopify.com/admin/api/2023-07/metafields.json?metafield%5Bowner_id%5D='.$id.'&metafield%5Bowner_resource%5D='.$type);
	curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
	curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'GET');
	
	
	$headers = array();
	$headers[] = 'X-Shopify-Access-Token: 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';
	curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);
	
	$result = json_decode(curl_exec($ch),true);
	if (curl_errno($ch)) {
	    echo 'Error:' . curl_error($ch);
	}
	curl_close($ch);
	
	return $result;

}

foreach($result['products'] as $Product){
	$meta = getMeta($Product['id'],'product');
	print_r($meta);
	$dashboardtitle = $Product['title'];
	foreach($meta['metafields'] as $field2){
		if($field2['key']=='dashboard_name'){
			$dashboardtitle = $field2['value'];
		}		
	}
	foreach($meta['metafields'] as $field){
		if($field['key']=='show_on_dashboard'){
			if($field['value']!==0 AND !empty($field['value'])){
				$show = 1;	
			}else{
				$show = 0;
			}
			echo '<h2>'.$Product['title'].'</h2>';
			echo '<h3>Dashboard Title: '.$dashboardtitle.' - '.$Product['id'].'</h3>';
			$sql = "INSERT INTO shopify_products (productid, variantid, title, dashboardtitle, showproduct)
			VALUES ('".$Product['id']."', '".$Product['id']."', '".addslashes($Product['title'])."', '".addslashes($dashboardtitle)."', '".$show."')";
			$conn->query($sql);	
			if(count($Product['variants'])>0){
				foreach($Product['variants'] as $variant){
					$meta = getMeta($variant['id'],'variant');
					foreach($meta['metafields'] as $field3){
						if($field3['key']=='dashboard_name'){
							$dashboardtitle = $field3['value'];
						}		
					}
					foreach($meta['metafields'] as $vmeta){
						if($vmeta['key']=='dashboard_name'){
							echo $vmeta['value'].' - '.$variant['id'].'<br />';
							if($vmeta['value']){
								$dashboardtitle = $vmeta['value'];
							}else{
								$dashboardtitle = $variant['title'];
							}
							$sql = "INSERT INTO shopify_products (productid, variantid, title, dashboardtitle, showproduct)
							VALUES ('".$Product['id']."', '".$variant['id']."', '".addslashes($Product['title'])."', '".addslashes($dashboardtitle)."', '".$show."')";
							$conn->query($sql);
						}
					}
				}
			}
			echo "<hr />";
			sleep(2);
		}
	}
}

$conn->close();
?>