<?php
ini_set('display_errors', 1);
ini_set('display_startup_errors', 1);
error_reporting(E_ALL);

$servername = "localhost";
$username = "wheeliams_dashboard";
$password = "EGalEh1x..r3";
$dbname = "wheeliams_dashboard";

// Create connection
$conn = new mysqli($servername, $username, $password, $dbname);
// Check connection
if ($conn->connect_error) {
  die("Connection failed: " . $conn->connect_error);
}

// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
$ch = curl_init();

curl_setopt($ch, CURLOPT_URL, 'https://wheeliamsltd.myshopify.com/admin/api/2023-10/orders.json?status=open&limit=250');
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'GET');


$headers = array();
$headers[] = 'X-Shopify-Access-Token: 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';
curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

$result = json_decode(curl_exec($ch),true);
if (curl_errno($ch)) {
    echo 'Error:' . curl_error($ch);
}
curl_close($ch);

//print_r($result);

function getProduct($id){
	// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
	$ch = curl_init();
	
	curl_setopt($ch, CURLOPT_URL, 'https://wheeliamsltd.myshopify.com/admin/api/2023-10/products/'.$id.'.json');
	curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
	curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'GET');
	
	
	$headers = array();
	$headers[] = 'X-Shopify-Access-Token: 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';
	curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);
	
	$result = json_decode(curl_exec($ch),true);
	if (curl_errno($ch)) {
	    echo 'Error:' . curl_error($ch);
	}
	curl_close($ch);
	
	return $result;

}

function getMeta($id){
	// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
	$ch = curl_init();
	
	curl_setopt($ch, CURLOPT_URL, 'https://wheeliamsltd.myshopify.com/admin/api/2023-07/metafields.json?metafield%5Bowner_id%5D='.$id.'&metafield%5Bowner_resource%5D=variants');
	curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
	curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'GET');
	
	
	$headers = array();
	$headers[] = 'X-Shopify-Access-Token: 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';
	curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);
	
	$result = json_decode(curl_exec($ch),true);
	if (curl_errno($ch)) {
	    echo 'Error:' . curl_error($ch);
	}
	curl_close($ch);
	
	foreach($result['metafields'] as $meta){
		if($meta['key']=='dashboard_name'){
			return $meta['value'];
		}
	}

}

function getProductDB($conn,$id){
	
	if($id<>''){
		$sql = "SELECT * FROM shopify_products WHERE variantid='".$id."'";
		$result = $conn->query($sql);
		
		if ($result->num_rows == 1) {
			while($row = $result->fetch_assoc()) {
				return $row;
			}
		} else {
			$sql = "SELECT * FROM shopify_products WHERE productid=".$id;
			$result = $conn->query($sql);
			if ($result->num_rows == 1) {
				// output data of each row
				while($row = $result->fetch_assoc()) {
					return $row;
				}
			}
		}
	}
	
}

foreach($result['orders'] as $Order){
	//print_r($Order);
	$show = false;
	$products = '';
	
	foreach($Order['line_items'] as $item){
		print_r($item);
		echo $item['variant_id'];
		//$metaData = getProduct($item['variant_id']);
		$productData = getProductDB($conn,$item['variant_id']);
		if($productData['dashboardtitle']){
			$products .= "$productData[dashboardtitle]<br />";	
		}else{
			$products .= "$item[title]<br />";
		}
		$show = true;
	}
	if($show){
		echo "<p><strong>".$Order['name']."</strong><br />";
		echo $Order['contact_email']."<br />";
		echo $Order['created_at']."<br />";
		echo $products;
	}
	echo "<hr />";
}
?>