<link rel="stylesheet" href="/admin/addons/apps/wheeliams/assets/styles.css" />
<link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/fullcalendar/3.8.0/fullcalendar.min.css" />
<link rel="stylesheet" href="/admin/addons/apps/wheeliams/assets/fullcalendar-scheduler/scheduler.css" />

<script src="https://code.jquery.com/jquery-3.2.1.min.js" integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4=" crossorigin="anonymous"></script>
<script type="text/javascript" src="/admin/addons/apps/wheeliams/assets/moment.js"></script>
<script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/fullcalendar/3.8.0/fullcalendar.min.js"></script>
<script src='/admin/addons/apps/wheeliams/assets/fullcalendar-scheduler/scheduler.js'></script>

<link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/css/select2.min.css" rel="stylesheet" />
<script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/js/select2.min.js"></script>

<script src="/admin/addons/apps/wheeliams/html5-qrcode.min.js"></script>

<script>
$(document).ready(function() {
    $('select[name!=countryOfOrigin]').select2({
	    width:'resolve'
    });
});
</script>

<style>
	.select2-container{
		min-width:120px !important;
	}
	.field-wrap.spec{
		padding-top:0px;
		margin-top:-5px;
	}
</style>

</script>