<?php

ini_set('display_errors', 1);
ini_set('display_startup_errors', 1);
error_reporting(E_ALL);

$headers = array();
$headers[] = 'X-Shopify-Access-Token: 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';

// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
$ch = curl_init();

curl_setopt($ch, CURLOPT_URL, 'https://wheeliamsltd.myshopify.com/admin/api/2024-04/metafields.json?metafield%5Bowner_id%5D=7815866712287&metafield%5Bowner_resource%5D=product');
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'GET');


$headers = array();
$headers[] = 'X-Shopify-Access-Token: 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';
curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

$result = curl_exec($ch);
if (curl_errno($ch)) {
    echo 'Error:' . curl_error($ch);
}
curl_close($ch);

print_r(json_decode($result,true));

// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
$ch = curl_init();

curl_setopt($ch, CURLOPT_URL, 'https://wheeliamsltd.myshopify.com/admin/api/2024-04/products/7815866712287/metafields/28204744900831.json');
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'GET');

$headers = array();
$headers[] = 'X-Shopify-Access-Token: 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';
curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

$result = curl_exec($ch);
if (curl_errno($ch)) {
    echo 'Error:' . curl_error($ch);
}
curl_close($ch);
echo "<hr />";
print_r(json_decode($result,true));
